### ISSUE TITLE
Привилегии ломаются при смене расы

### ISSUE THREAD

**Issue by weqqr** [weqqr/lord#11]

**Comment by narrnika** [comment]
1. Для обычных игроков не фатально, ибо никаких привилегий, кроме расовых, они не имеют.
2. В качестве костыля - в функции classes.set_race читать набор текущих привилегий, и заменять только расовые.
    * Тут могут возникнуть неувязки - к примеру fly - расовая привилегия для тени, но у модераторов она независимо от расы.
    * Как один из вариантов решения - выделение админа и модераторов в самостоятельные расы с соответствующими наборами привилегий и скинов.
3. В идеале - полная смена механизма рас с привилегий на скрытые инвентари.
