### ISSUE TITLE
upgrade 0.4.14

### ISSUE THREAD

**Issue by narrnika** [weqqr/lord#26]
https://github.com/minetest/minetest/tree/stable-0.4
Будем, нет? Для начала, видимо, на полигон?

**Comment by Mikola314** [comment]
поддерживаю

**Comment by albel4** [comment]
собирать будем с CURSES_LIBRARY?

**Comment by narrnika** [comment]
Это типа терминал внешний?.. вряд ли, не вижу особой необходимости, тем более, что оно tty занимает вроде бы.. короче, если с ним не пройдёт или самой ncurses ещё нету, то можно не мучаться, имхо.

**Comment by albel4** [comment]
тогда поехали....!

**Comment by Mikola314** [comment]
За двое суток периодических беганий и ковыряний на полигоне, новых багов и проблем не выявлено.
Предлагаем ( с narrnika) сделать копию текущего движка основного сервера LORD, скомпилировать новую версию для него и подменить. 
Народу в последнее время мало. Если и будут косяки и глюки из-за непредвиденных ситуаций - народ не заметит.

**Comment by Mikola314** [comment]
Есть смысл закрыть тему. Обновление прошло успешно, пока багов не обнаружено.
