### ISSUE TITLE
Уязвимость! Факела, отвёртка и блоки.

### ISSUE THREAD

**Issue by Mikola314** [weqqr/lord#27]
Устанавливаем факел, разворачиваем факел отвёрткой по ПКМ, устанавливаем рядом любой блок, сервер падает. На прошлой версии сервера факела осыпались как лут. 
При запуске свежего дефолтного мира на последней версии, факела отвёрткой вообще не поворачиваются.

**Comment by Mikola314** [comment]
Есть мнение, что виноваты отвёртки. Замечен не фатальный баг с текстурой: при включённой настройке "стекло без швов"  при повороте стекла по ЛКМ появляется глючная текстурка (квадрат залитый рандомным цветом)

**Comment by narrnika** [comment]
Вроде поправил, залил на сервер. Тестируем.

**Comment by weqqr** [comment]
7af03775a6bb6013b6adc9870000035011388e57
