### ISSUE TITLE
“Арбузы” или “Кто убил Кадзи?”

### ISSUE THREAD

**Issue by albel4** [weqqr/lord#5]
Есть объекты lottfarming:melon (“Арбуз” - долька арбуза) и lottfarming:melon_3 (“Арбуз” - кубический арбуз с грядки). Есть крафт из 9 шт lottfarming:melon (дольки) получается 1 шт  lottfarming:melon (опять долька).
Надо исправить на выходе на lottfarming:melon_3. Нужна схема обратного крафта из lottfarming:melon_3 в 9 шт lottfarming:melon. Желательно поправить лут при срывании с грядки lottfarming:melon_3 (сейчас сыпятся дольки и семена, желательно просто lottfarming:melon 1 шт).

**Comment by narrnika** [comment]
сборка из долек арбуза - весьма сомнительный проект, без клея не обойтись.. может так: срываем целый арбуз, крафтим его на 9 долек, каждую дольку - либо сожрать, либо крафтить на семена

**Comment by narrnika** [comment]
Исправлено, можно проверять и закрывать:
https://github.com/weqqr/lord/commit/c07e7ebbd43a69097977f90b692ba62c57a1e7d4
https://github.com/weqqr/lord/commit/e349dcac174a98fd23917ebc06bca30e60b4fc43

**Comment by weqqr** [comment]
:+1:
